#!/bin/sh

OPEN_FAAS_ADDR="http://127.0.0.1:8080"
KOTLIN_NATIVE_VER="0.7.1"
KOTLIN_NATIVE_HOME="$HOME/kotlin-native-linux-$KOTLIN_NATIVE_VER"
PROGRAM="handler"
IMAGE="hello-kotlin"

echo 'Compiling Kotlin Native program...'
$KOTLIN_NATIVE_HOME/bin/konanc -opt -o $PROGRAM main.kt
mv "$PROGRAM.kexe" $PROGRAM

echo 'Building Docker image...'
docker build --tag $IMAGE .
echo "The $IMAGE image is ready to be deployed to OpenFaaS on $OPEN_FAAS_ADDR"
